version: "3.9"
services:
  wp:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      DATABASE_URL: mysql://root:secret@db/wp
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: wp
